apiVersion: v1
kind: Service
metadata:
  name: apigateway-srv
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
    - name: apigateway
      protocol: TCP
      port: 80
      targetPort: 80