apiVersion: apps/v1
kind: Deployment
metadata: 
  name: notification-depl
spec:
  replicas: 1 #basically kubernetes makes sure even if our service dies that it starts it again, hence the replica = 1. There must always be at least 1 replica.
  selector: 
    matchLabels: 
      app: notificationservice
  template:
    metadata: 
      labels: 
        app: notificationservice
    spec:
      containers:
        - name: notificationservice
          image: maxxburn/notificationservice:latest