apiVersion: v1
kind: Service
metadata:
  name: homelayout-srv
spec:
  type: NodePort
  selector:
    app: homelayoutservice
  ports:
    - name: homelayoutservice
      protocol: TCP
      port: 80
      targetPort: 80