apiVersion: v1
kind: Service
metadata:
  name: privilegeservice-srv
spec:
  type: NodePort
  selector:
    app: privilegeservice
  ports:
    - name: privilegeservice
      protocol: TCP
      port: 80
      targetPort: 80